### ISSUE TITLE
sperf core statuslogger --diagdir <dir> output misses to identify DSE & C* versions

### ISSUE THREAD

**Issue by msmygit** [DataStax-Toolkit/sperf#15]
Output of `sperf core statuslogger --diagdir <dir>` command is unable to determine the DSE & C* version as shown below. This was run against `DSE 6.7.3` version,

```
dse versions: {'6.x'}
cassandra versions: unknown
```

**Comment by rssvihla** [comment]
This is as intended:

* For statuslogger there isn't much diagnostic difference between DSE versions as all the code is the same for 6.x versions.
* There is no valid "Cassandra version" that is the equivalent for DES 6.x

For proper versioning detection you can try the base `sperf` command or the `sperf core diag` command. Again the Cassandra version does not actually make any sense for DSE 6 and later as it is a closed source fork.
