### ISSUE TITLE
sperf -v core schema commands doesn't work on a DSE 5.1.0 cluster

### ISSUE THREAD

**Issue by msmygit** [DataStax-Toolkit/sperf#17]
`sperf -v core schema --diagdir $DDIR` command when run on a DSE `5.1.0` gives the following output,

```
sperf core schema: 0.6.0


Keyspace Count  : 0
Table Count     : 0
2i Count        : 0
MV Count        : 0
Solr Index Count: 0
Solr Table Count: 0
```

**Comment by foundev** [comment]
Not able to reproduce this, I just think your tarball is missing the schema file. I can improve the output to show the number of files processed by default (you can see this with the -p flag but it only works on some tooling).

Either way this is not an issue with 5.1.0 tarballs
