### ISSUE TITLE
https://datastax-toolkit.github.io/sperf/ link isn't working

### ISSUE THREAD

**Issue by prabinsh** [DataStax-Toolkit/sperf#59]
https://datastax-toolkit.github.io/sperf/ isn't working.

**Comment by rsds143** [comment]
Thank you for the catch I switched to direct links to the MD files until I have a chance to debug what broke on GitHub pages with the branch rename (supposedly this is all supported and won’t break, but here we are).

will keep the issue open though until I get GitHub pages back

**Comment by rsds143** [comment]
Workaround url https://github.com/DataStax-Toolkit/sperf/blob/main/docs/index.md

**Comment by rsds143** [comment]
Thanks again for noticing, everything is fixed. Once I committed the workaround the page started rendering again so I have just flipped everything back and tested it after the last GitHub pages build.
